export enum Technologies {
  html = 'HTML',
  css = 'CSS',
  sass = 'SASS',
  javascript = 'JavaScript',
  react = 'React.js',
  typescript = 'TypeScript',
  redux = 'Redux',
  reduxToolkit = 'Redux Toolkit',
  next = 'Next.js',
  mui = 'Material UI',
  tanStackQuery = 'TanStack Query',
  git = 'Git',
  gitHub = 'GitHub',
  npm = 'npm',
  restApi = 'RESTful API',
  router = 'React Router',
  context = 'React Context',
  figma = 'Figma',
  vsCode = 'VS Code'
}
